-- Fix few_shot_examples to use black background (consistent with system_prompt)

UPDATE agents
SET few_shot_examples = '[
    {"human": "cute cartoon sticker, big eyes, smiling", "ai": "{\"ok\": true, \"prompt\": \"Create a high-quality messenger sticker. Style: cute cartoon style with big expressive eyes. Character: Use the character from the provided photo as the base. Preserve recognizable facial features, proportions, and overall likeness. Concept: smiling, cheerful expression. Composition: Character occupies maximum canvas area, bold white border around the character (approx 25% outline width), smooth and uniform border. Visual design: Clean bold sticker outline, high contrast, simplified shapes, flat shading, pastel color palette. Requirements: black background, no watermark, no logo, no frame, no text. Quality: Expressive, visually appealing, optimized for messenger sticker.\", \"retry\": false}"},
    {"human": "симпсоны", "ai": "{\"ok\": true, \"prompt\": \"Create a high-quality messenger sticker. Style: The Simpsons cartoon style with yellow skin tone, flat 2D look, simple bold outlines, minimal shading. Character: Use the character from the provided photo as the base. Preserve recognizable facial features, proportions, and overall likeness. Concept: neutral expression in Simpsons universe style. Composition: Character occupies maximum canvas area, bold white border around the character (approx 25% outline width), smooth and uniform border. Visual design: Clean bold sticker outline, high contrast, simplified shapes, flat shading, bright saturated colors. Requirements: black background, no watermark, no logo, no frame, no text. Quality: Expressive, visually appealing, optimized for messenger sticker.\", \"retry\": false}"},
    {"human": "аниме, грустный", "ai": "{\"ok\": true, \"prompt\": \"Create a high-quality messenger sticker. Style: anime style with clean lines and soft shading. Character: Use the character from the provided photo as the base. Preserve recognizable facial features, proportions, and overall likeness. Concept: sad, melancholic expression. Composition: Character occupies maximum canvas area, bold white border around the character (approx 25% outline width), smooth and uniform border. Visual design: Clean bold sticker outline, high contrast, expressive anime eyes, soft cel-shading, vibrant colors. Requirements: black background, no watermark, no logo, no frame, no text. Quality: Expressive, visually appealing, optimized for messenger sticker.\", \"retry\": false}"},
    {"human": "сделай красиво", "ai": "{\"ok\": false, \"prompt\": null, \"retry\": true}"},
    {"human": "любой стиль на твой выбор", "ai": "{\"ok\": false, \"prompt\": null, \"retry\": true}"}
  ]'::jsonb,
    updated_at = now()
WHERE name = 'prompt_generator';
